baseURL = 'https://blogpre.3css.com/'
languageCode = 'zh-CN'
title = 'x2'
theme = 'hugo-book'
hasCJKLanguage = true

googleAnalytics = "G-0R5FWRP8MH-x2"
disqusShortname = "mtfront-x2"

[markup]
    [markup.highlight]
        style = 'paraiso-light'     # style demos https://pygments.org/demo/
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true    # 允许渲染原始 HTML

[params]
    BookRepo = 'https://github.com/cmdfas/test-gh-actions'
    BookLogo = 'dino.gif'
    BookMenuBundle = '/menu'
    
    [params.cdnPrefixes]
        default = "https://static.cmdfas.top"
        cn = "https://static.3css.com"
        en = "https://static.cmdfas.top"


